export const queryKeys = {
  products: {
    all: ['products'] as const,
    lists: () => ['products', 'list'] as const,
    list: <P extends object>(params: P) => ['products', 'list', params] as const,
    details: () => ['products', 'detail'] as const,
    detail: (id: number | string) => ['products', 'detail', id] as const,
    search: (q: string) => ['products', 'search', q] as const,
    importStatus: (id: number | string) => ['products', 'import-status', id] as const,
  },
  categories: {
    all: ['categories'] as const,
    lists: () => ['categories', 'list'] as const,
    list: <P extends object>(params: P) => ['categories', 'list', params] as const,
    details: () => ['categories', 'detail'] as const,
    detail: (id: number | string) => ['categories', 'detail', id] as const,
    featured: (page: number, perPage: number) => ['categories', 'featured', { page, perPage }] as const,
    filter: (q: string) => ['categories', 'filter', q] as const,
    importStatus: (id: number | string) => ['categories', 'import-status', id] as const,
    exportStatus: (id: number | string) => ['categories', 'export-status', id] as const,
  },
  brands: {
    all: ['brands'] as const,
    lists: () => ['brands', 'list'] as const,
    list: <P extends object>(params: P) => ['brands', 'list', params] as const,
    details: () => ['brands', 'detail'] as const,
    detail: (id: number | string) => ['brands', 'detail', id] as const,
    productSearch: (q: string) => ['brands', 'product-search', q] as const,
  },
  tags: {
    all: ['tags'] as const,
    lists: () => ['tags', 'list'] as const,
    list: <P extends object>(params: P) => ['tags', 'list', params] as const,
    details: () => ['tags', 'detail'] as const,
    detail: (id: number | string) => ['tags', 'detail', id] as const,
  },
  sliders: {
    all: ['sliders'] as const,
    lists: () => ['sliders', 'list'] as const,
    list: <P extends object>(params: P) => ['sliders', 'list', params] as const,
    details: () => ['sliders', 'detail'] as const,
    detail: (id: number | string) => ['sliders', 'detail', id] as const,
    filter: (q: string) => ['sliders', 'filter', q] as const,
    productSearch: (q: string) => ['sliders', 'product-search', q] as const,
  },
  flashSales: {
    all: ['flash-sales'] as const,
    lists: () => ['flash-sales', 'list'] as const,
    list: <P extends object>(params: P) => ['flash-sales', 'list', params] as const,
    details: () => ['flash-sales', 'detail'] as const,
    detail: (id: number | string) => ['flash-sales', 'detail', id] as const,
    filter: (q: string) => ['flash-sales', 'filter', q] as const,
    productSearch: (q: string) => ['flash-sales', 'product-search', q] as const,
  },
  banners: {
    all: ['banners'] as const,
    lists: () => ['banners', 'list'] as const,
    list: <P extends object>(params: P) => ['banners', 'list', params] as const,
    details: () => ['banners', 'detail'] as const,
    detail: (id: number | string) => ['banners', 'detail', id] as const,
    productSearch: (q: string) => ['banners', 'product-search', q] as const,
  },
  orders: {
    all: ['orders'] as const,
    lists: () => ['orders', 'list'] as const,
    list: <P extends object>(params: P) => ['orders', 'list', params] as const,
    details: () => ['orders', 'detail'] as const,
    detail: (id: number | string) => ['orders', 'detail', id] as const,
    myOrders: {
      all: ['orders', 'my'] as const,
      list: <P extends object>(params: P) => ['orders', 'my', 'list', params] as const,
    },
  },
  invoices: {
    all: ['invoices'] as const,
    lists: () => ['invoices', 'list'] as const,
    list: <P extends object>(params: P) => ['invoices', 'list', params] as const,
    details: () => ['invoices', 'detail'] as const,
    detail: (id: number | string) => ['invoices', 'detail', id] as const,
    verify: (uuid: string) => ['invoices', 'verify', uuid] as const,
  },
  users: {
    all: ['users'] as const,
    lists: () => ['users', 'list'] as const,
    list: <P extends object>(params: P) => ['users', 'list', params] as const,
    roles: () => ['users', 'roles'] as const,
    search: (q: string) => ['users', 'search', q] as const,
    detail: (id: number | string) => ['users', 'detail', id] as const,
  },
  roles: {
    all: ['roles'] as const,
    lists: () => ['roles', 'list'] as const,
    list: <P extends object>(params: P) => ['roles', 'list', params] as const,
    details: () => ['roles', 'detail'] as const,
    detail: (id: number | string) => ['roles', 'detail', id] as const,
    permissions: () => ['roles', 'permissions'] as const,
  },
  coupons: {
    all: ['coupons'] as const,
    lists: () => ['coupons', 'list'] as const,
    list: <P extends object>(params: P) => ['coupons', 'list', params] as const,
    details: () => ['coupons', 'detail'] as const,
    detail: (id: number | string) => ['coupons', 'detail', id] as const,
    assignments: {
      all: (couponId: number) => ['coupons', couponId, 'assignments'] as const,
      list: <P extends object>(couponId: number, params: P) => ['coupons', couponId, 'assignments', params] as const,
    },
  },
  reviews: {
    all: ['reviews'] as const,
    lists: () => ['reviews', 'list'] as const,
    list: <P extends object>(params: P) => ['reviews', 'list', params] as const,
    details: () => ['reviews', 'detail'] as const,
    detail: (id: number | string) => ['reviews', 'detail', id] as const,
  },
  siteReviews: {
    all: ['site-reviews'] as const,
    lists: () => ['site-reviews', 'list'] as const,
    list: <P extends object>(params: P) => ['site-reviews', 'list', params] as const,
    details: () => ['site-reviews', 'detail'] as const,
    detail: (id: number | string) => ['site-reviews', 'detail', id] as const,
  },
  faqs: {
    all: ['faqs'] as const,
    lists: () => ['faqs', 'list'] as const,
    list: <P extends object>(params: P) => ['faqs', 'list', params] as const,
    details: () => ['faqs', 'detail'] as const,
    detail: (id: number | string) => ['faqs', 'detail', id] as const,
  },
  staticPages: {
    all: ['static-pages'] as const,
    lists: () => ['static-pages', 'list'] as const,
    list: () => ['static-pages', 'list'] as const,
    details: () => ['static-pages', 'detail'] as const,
    detail: (slug: string) => ['static-pages', 'detail', slug] as const,
    preview: (slug: string, lang: string) => ['static-pages', 'preview', slug, lang] as const,
  },
  sections: {
    all: ['sections'] as const,
    lists: () => ['sections', 'list'] as const,
    list: <P extends object>(params: P) => ['sections', 'list', params] as const,
    details: () => ['sections', 'detail'] as const,
    detail: (id: number | string) => ['sections', 'detail', id] as const,
    sectionTypes: () => ['sections', 'section-types'] as const,
    typeSettings: (typeName: string) => ['sections', 'section-types', typeName, 'settings'] as const,
    productTypes: () => ['sections', 'product-types'] as const,
    entitySearch: (endpoint: string, q: string) => ['sections', 'entity-search', endpoint, q] as const,
    entitySearchInfinite: (endpoint: string, q: string) => ['sections', 'entity-search-infinite', endpoint, q] as const,
  },
  promotions: {
    all: ['promotions'] as const,
    lists: () => ['promotions', 'list'] as const,
    list: <P extends object>(params: P) => ['promotions', 'list', params] as const,
    details: () => ['promotions', 'detail'] as const,
    detail: (id: number | string) => ['promotions', 'detail', id] as const,
    productSearch: (q: string) => ['promotions', 'product-search', q] as const,
  },
  attributes: {
    all: ['attributes'] as const,
    lists: () => ['attributes', 'list'] as const,
    list: <P extends object>(params: P) => ['attributes', 'list', params] as const,
    details: () => ['attributes', 'detail'] as const,
    detail: (id: number | string) => ['attributes', 'detail', id] as const,
  },
  contacts: {
    all: ['contacts'] as const,
    lists: () => ['contacts', 'list'] as const,
    list: <P extends object>(params: P) => ['contacts', 'list', params] as const,
    details: () => ['contacts', 'detail'] as const,
    detail: (id: number | string) => ['contacts', 'detail', id] as const,
  },
  settings: {
    all: ['settings'] as const,
  },
  profile: {
    all: ['profile'] as const,
  },
  shops: {
    all: ['shops'] as const,
    lists: () => ['shops', 'list'] as const,
    list: <P extends object>(params: P) => ['shops', 'list', params] as const,
  },
  activityLogs: {
    all: ['activity-logs'] as const,
    lists: () => ['activity-logs', 'list'] as const,
    list: <P extends object>(params: P) => ['activity-logs', 'list', params] as const,
  },
  notifications: {
    all: ['notifications'] as const,
    lists: () => ['notifications', 'list'] as const,
    list: <P extends object>(params: P) => ['notifications', 'list', params] as const,
    unreadLists: () => ['notifications', 'unread'] as const,
    unreadList: <P extends object>(params: P) => ['notifications', 'unread', params] as const,
    count: () => ['notifications', 'count'] as const,
  },
  currencies: {
    all: ['currencies'] as const,
    lists: () => ['currencies', 'list'] as const,
    list: <P extends object>(params: P) => ['currencies', 'list', params] as const,
    details: () => ['currencies', 'detail'] as const,
    detail: (id: number | string) => ['currencies', 'detail', id] as const,
    rates: (currencyId: number | string, effectiveDate?: string) =>
      ['currencies', 'rates', currencyId, effectiveDate] as const,
    rate: (id: number | string) => ['currencies', 'rate', id] as const,
  },
  pickupLocations: {
    all: ['pickup-locations'] as const,
    lists: () => ['pickup-locations', 'list'] as const,
    list: <P extends object>(params: P) => ['pickup-locations', 'list', params] as const,
    details: () => ['pickup-locations', 'detail'] as const,
    detail: (id?: number | string) => ['pickup-locations', 'detail', id] as const,
  },
  shipping: {
    countries: {
      all: ['shipping', 'countries'] as const,
      lists: () => ['shipping', 'countries', 'list'] as const,
      list: <P extends object>(params: P) => ['shipping', 'countries', 'list', params] as const,
      details: () => ['shipping', 'countries', 'detail'] as const,
      detail: (id: number | string) => ['shipping', 'countries', 'detail', id] as const,
    },
    governorates: {
      all: ['shipping', 'governorates'] as const,
      lists: () => ['shipping', 'governorates', 'list'] as const,
      list: <P extends object>(params: P) => ['shipping', 'governorates', 'list', params] as const,
      details: () => ['shipping', 'governorates', 'detail'] as const,
      detail: (id: number | string) => ['shipping', 'governorates', 'detail', id] as const,
    },
    cities: {
      all: ['shipping', 'cities'] as const,
      lists: () => ['shipping', 'cities', 'list'] as const,
      list: <P extends object>(params: P) => ['shipping', 'cities', 'list', params] as const,
      details: () => ['shipping', 'cities', 'detail'] as const,
      detail: (id: number | string) => ['shipping', 'cities', 'detail', id] as const,
    },
  },
  dashboard: {
    all: ['dashboard'] as const,
    overview: () => ['dashboard', 'overview'] as const,
    revenue: () => ['dashboard', 'revenue'] as const,
    orderStats: () => ['dashboard', 'order-stats'] as const,
    recentOrders: (limit: number) => ['dashboard', 'recent-orders', limit] as const,
    topProducts: (limit: number) => ['dashboard', 'top-products', limit] as const,
    categoryStats: (language?: string) => ['dashboard', 'category-stats', language] as const,
    lowStock: (limit: number) => ['dashboard', 'low-stock', limit] as const,
    sales: () => ['dashboard', 'sales'] as const,
    customers: () => ['dashboard', 'customers'] as const,
    dashboardProducts: () => ['dashboard', 'products'] as const,
    dashboardOrders: () => ['dashboard', 'orders'] as const,
    dashboardCategories: () => ['dashboard', 'categories'] as const,
    dashboardCoupons: () => ['dashboard', 'coupons'] as const,
    dashboardCart: () => ['dashboard', 'cart'] as const,
    dashboardFinance: () => ['dashboard', 'finance'] as const,
  },
  currencyRates: {
    all: ['currency-rates'] as const,
    lists: () => ['currency-rates', 'list'] as const,
    list: <P extends object>(params: P) => ['currency-rates', 'list', params] as const,
    details: () => ['currency-rates', 'detail'] as const,
    detail: (id: number | string) => ['currency-rates', 'detail', id] as const,
  },
}
